source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-analytics'
gem 'jekyll-feed'
gem 'jekyll-multiple-languages-plugin'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-twitter-plugin'
gem "jekyll_github_sample", git: "https://github.com/bwillis/jekyll-github-sample", ref: 'master'